### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by LiteCat0905** [funnygeeker/keiyume#2]
![image](https://user-images.githubusercontent.com/101038478/203878809-4051267e-0641-4e14-9872-74548dca6594.png)
文档错误

**Comment by funnygeeker** [comment]
您好，可以问一下您觉得哪里出错了呢？

**Comment by funnygeeker** [comment]
您好，可以问一下您觉得哪里出错了呢？

**Comment by LiteCat0905** [comment]
> 

大哥查询数据为什么是new

**Comment by funnygeeker** [comment]
好的，我瞎了，感谢您的提醒((유∀유|||))
